#!/bin/bash
: '
The following script calculates
the square value of the number, 5.
'
((area=5*5))
echo $area
------------------------------------
#!/bin/bash

# Add two numeric value
((sum=25+35))

#Print the result
echo $sum
